legendry/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  root 'welcome#index'
  resources :organizations do
    resources :specifications do
      resources :entries do
        member do
          post 'commit'
        end
      end
    end
  end
end

legendry/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

legendry/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :specification
  validates :title, presence: true
  validates :description, presence: true

  def number_description
    n = number.nil? ? "TBD" : number.to_s
    (parent_number.nil? || parent_number.empty?) ? n : "#{parent_number}.#{n}"
  end
end

legendry/app/models/organization.rb
class Organization < ApplicationRecord
  has_many :specifications
  validates :name, presence: true
end

legendry/app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :organization
  has_many :entries
  validates :title, presence: true
end

legendry/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

legendry/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

legendry/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entries = Entry.where(specification_id: params[:specification_id])
  end

  def new
    @spec = Specification.find(params[:specification_id])
    @organization = Organization.find(params[:organization_id])
    @entry = Entry.new(parent_number: params[:parent_number])
  end

  def edit
    @entry = Entry.find(params[:id])
    puts (@entry.parent_number.empty? ? "nil" : @entry.parent_number)
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      redirect_to organization_specification_path(
        params[:organization_id],
        params[:specification_id]
      )
    else
      render 'edit'
    end
  end

  def create
    @spec = Specification.find(params[:specification_id])
    @organization = Organization.find(params[:organization_id])
    @entry = Entry.new entry_params
    @entry.specification_id = params[:specification_id]

    if @entry.save
      redirect_to organization_specification_path(
        params[:organization_id],
        params[:specification_id]
      )
    else
      render 'new'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to organization_specification_path(
      params[:organization_id],
      params[:specification_id]
    )
  end

  def commit
    @entry = Entry.find(params[:id])
    if @entry.number.nil?
      # determine the next number by:
      #   1. counting all of the siblings that have numbers
      #   2. adding 1 to the result
      #
      #   because you can currently delete an entry, if you do so, you lose
      #   that number forever, this will be addressed in the future
      all_siblings = Entry.where(parent_number: @entry.parent_number)
      @siblings = all_siblings.where.not(number: nil).or(all_siblings.where.not(number: ''))
      @entry.number = @siblings.count+1
      @entry.save
    end
  end

  private

  def entry_params
    params[:entry].permit(:title, :description, :parent_number)
  end
end

legendry/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.user_id = current_user.id

    if @organization.save
      redirect_to @organization
    else
      render 'new'
    end
  end

  def show
    @organization = Organization.find(params[:id])
    @specs = @organization.specifications
  end

  def index
    @organizations = Organization.where user_id: current_user.id
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update(organization_params)
      redirect_to @organization
    else
      render 'edit'
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    redirect_to organizations_path
  end

  private

  def organization_params
    params[:organization].permit(:name)
  end
end

legendry/app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @organization = Organization.find(params[:organization_id])
    @spec = @organization.specifications.build
  end

  def create
    @organization = Organization.find(params[:organization_id])
    @spec = Specification.new(specification_params)
    @spec.organization_id = @organization.id

    if @spec.save
      redirect_to organization_specification_path(@organization, @spec)
    else
      render 'new'
    end
  end

  def show
    @spec = Specification.find(params[:id])
    @entries = Entry
      .where(specification_id: @spec.id)
      .sort_by { |e|
        # TODO: 1000 here is arbitrary, I don't like it. I'd prefer a better system for picking a number.
        # but it ensures that TBD entries show up at the bottom of the list (if the list is less than 1000.
        # It also allows me to move on for the time being.
        num = e.number.nil? ? 1000 : e.number
        e.parent_number.nil? ? [num] : (e.parent_number.split('.').map(&:to_i) + [num])
      }
  end

  def index
    @organization = Organization.find(params[:organization_id])
    @specs = @organization.specifications
  end

  def edit
    @spec = Specification.find(params[:id])
  end

  def update
    @spec = Specification.find(params[:id])
    if @spec.update(specification_params)
      redirect_to organization_specification_path(@spec.organization, @spec)
    else
      render 'edit'
    end
  end

  def destroy
    @spec = Specification.find(params[:id])
    @spec.destroy

    redirect_to organization_specifications_path
  end

  private

  def specification_params
    params[:specification].permit(:title)
  end
end

legendry/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @organizations = Organization.where user_id: current_user.id
  end
end

legendry/app/helpers/application_helper.rb
module ApplicationHelper
end

legendry/app/helpers/entries_helper.rb
module EntriesHelper
  def entry_header(entry)
    levels = entry.number_description.count('.') + 1
    "<h#{levels}> #{entry.number_description} #{entry.title} </h#{levels}>"
  end
end

legendry/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

legendry/app/helpers/specifications_helper.rb
module SpecificationsHelper
end

legendry/app/helpers/welcome_helper.rb
module WelcomeHelper
end

legendry/app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= form_with(model: [@entry.specification.organization, @entry.specification, @entry], local: true) do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %>
        prohibited this organization from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p><strong><%= @entry.number_description %></strong></p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<p>
  <%= button_to "Commit Entry", :action => :commit %>
</p>

<%= link_to "Back", organization_specification_path(@entry.specification.organization, @entry.specification) %>

legendry/app/views/entries/index.html.erb
<h1>Specification</h1>

<table>
  <tr>
    <th></th>
  </tr>

  <% @entries.each do |entry| %>
    <tr>
      <td><%= entry.title %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New entry', new_organization_specification_entry_path %>

legendry/app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with scope: :entry, url: organization_specification_entries_path(@organization, @spec), local: true do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@entry.errors.count, "error") %>
        prohibited this organization from being saved:
      </h2>
      <ul>
        <% @entry.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :number %><br>
    <%= text_field_tag 'temporary-number', @entry.number_description, disabled: true %>
  </p>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.hidden_field :parent_number %>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Back", organization_specifications_path(@spec.organization) %>

legendry/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Legendry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

legendry/app/views/organizations/edit.html.erb
<h1>Organization</h1>

<%= form_with(model: @organization, local: true) do |form| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@organization.errors.count, "error") %>
        prohibited this organization from being saved:
      </h2>
      <ul>
        <% @organization.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Back", organizations_path %>

legendry/app/views/organizations/index.html.erb
<h1>Organization</h1>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>

  <% @organizations.each do |organization| %>
    <tr>
      <td><%= organization.name %></td>
      <td><%= link_to 'Show', organization_path(organization) %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization_path(organization), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New organization', new_organization_path %>

legendry/app/views/organizations/new.html.erb
<h1>Organization</h1>

<%= form_with scope: :organization, url: organizations_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

legendry/app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>
<h2>Specifications</h2>

<table>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>

  <% @specs.each do |spec| %>
    <tr>
      <td><%= spec.title %></td>
      <td><%= link_to 'Show', organization_specification_path(spec.organization, spec) %></td>
      <td><%= link_to 'Edit', edit_organization_specification_path(spec.organization, spec) %></td>
      <td>
        <%= link_to 'Delete',
          organization_specification_path(spec.organization, spec),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New specification', new_organization_specification_path(@organization) %>

<%= link_to "Back", organizations_path %>

legendry/app/views/specifications/edit.html.erb
<h1>Specification</h1>

<%= form_with(model: [@spec.organization, @spec], local: true) do |form| %>
  <% if @spec.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@spec.errors.count, "error") %>
        prohibited this organization from being saved:
      </h2>
      <ul>
        <% @spec.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Back", organization_specifications_path(@spec.organization) %>

legendry/app/views/specifications/index.html.erb
<h1>Specifications</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>

  <% @specs.each do |spec| %>
    <tr>
      <td><%= spec.title %></td>
      <td><%= link_to 'Show', organization_specification_path(spec.organization, spec) %></td>
      <td><%= link_to 'Edit', edit_organization_specification_path(spec.organization, spec) %></td>
      <td>
        <%= link_to 'Delete',
          organization_specification_path(spec.organization, spec),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New specification', new_organization_specification_path(@organization) %>

legendry/app/views/specifications/new.html.erb
<h1>New Specification</h1>

<%= form_with scope: :specification, url: organization_specifications_path(@organization), local: true do |form| %>
  <% if @spec.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@spec.errors.count, "error") %>
        prohibited this organization from being saved:
      </h2>
      <ul>
        <% @spec.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to "Back", organization_specifications_path(@spec.organization) %>

legendry/app/views/specifications/show.html.erb
<h1><%= @spec.title %></h1>

<% @entries.each do |entry| %>
  <%= entry_header(entry).html_safe %>
  <blockquote><%= entry.description %></blockquote>
  <div>
      <%= link_to 'Edit', edit_organization_specification_entry_path(@spec.organization, @spec, entry) %>
    | <%= link_to 'Delete', organization_specification_entry_path(@spec.organization, @spec, entry), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% if !entry.number.nil? %>
      | <%= link_to 'New entry', new_organization_specification_entry_path(@spec.organization, @spec, :parent_number => "#{entry.number_description}") %>
    </div>
  <% end %>
<% end %>

<div>
    <%= link_to 'New entry', new_organization_specification_entry_path(@spec.organization, @spec) %>
  | <%= link_to "Back", organization_specifications_path(@spec.organization) %>
</div>

legendry/app/views/welcome/index.html.erb
<h2>Organizations</h2>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>

  <% @organizations.each do |organization| %>
    <tr>
      <td><%= organization.name %></td>
      <td><%= link_to 'Show', organization_path(organization) %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization_path(organization), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New organization', new_organization_path %>